# Generated by Django 3.0.3 on 2020-03-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200228_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(verbose_name='Money'),
        ),
    ]
